### ISSUE TITLE
Allow using CategoryWatchlist on Portuguese Wikipedia (and other wikis)

### ISSUE THREAD

**Issue by he7d3r** [bamyers99/Bambots#3]
As a user of non-English Wikipedia wikis, I would like to use
https://tools.wmflabs.org/bambots/CategoryWatchlist.php
for watching changes to the categories on those wikis. Is that possible?

**Comment by bamyers99** [comment]
I have added the Portuguese Wikipedia. Other wikis can be added if the Portuguese beta testing goes ok. Here is a [sample watchlist](https://tools.wmflabs.org/bambots/CategoryWatchlist.php?query=20caa6f529aa2f07983f358eef22bee8). The localization was done using Google translate, so feel free to suggest improvements.

**Comment by he7d3r** [comment]
Thank you! I proposed a few changes in the translations.

However, I wasn't able to make the timestamps to make sense in Portuguese. For example, where it shows "April 16, 2015 16th hora" we would use "17h00min de 16 de abril de 2015‎".

**Comment by bamyers99** [comment]
Thanks for the translation update. The timestamps have been localized with property datetimefmt. I am not sure what to do with the minute display. The bot runs once an hour at 45 minutes past the hour. Using 16th hora, I was trying to convey that the listed items were for the given hour.
