### ISSUE TITLE
TemplateParam.php for commonswiki

### ISSUE THREAD

**Issue by Krinkle** [bamyers99/Bambots#5]
Hi @bamyers99,

Thank you so much for creating this tool. I would like to request if it is possible to enable [TemplateParam.php](https://tools.wmflabs.org/bambots/TemplateParam.php) for <https://commons.wikimedia.org>?

**Comment by bamyers99** [comment]
This has been enabled for commonswiki.
See https://tools.wmflabs.org/bambots/TemplateParam.php?wiki=commonswiki&template=

**Comment by Krinkle** [comment]
Thanks! It's working for `Template:Information` but it seems to not work for `Template:Talkarchive`. Do you know why?


https://commons.wikimedia.org/wiki/Template:Talkarchive

https://tools.wmflabs.org/bambots/TemplateParam.php?wiki=commonswiki&template=Talkarchive
> Wiki: Wikipedia Commons
> Template: Talkarchive
>
> -------
> Monthly data as of 2018-05-01
> Messages:
> * Template not found
