### ISSUE TITLE
Question: how does it do counts in NavelGazer?

### ISSUE THREAD

**Issue by egonw** [bamyers99/Bambots#8]
Hi, first, thanks for you awesome tool! I learned about it only today.

I was wondering how it does the counting. If I look at https://bambots.brucemyers.com/NavelGazer.php?property=P235 then the counts are a lot lower than I expected:

![image](https://github.com/bamyers99/Bambots/assets/26721/34d9a9bd-42c6-425d-b4b2-7cecd9d1efd9)

There are plenty of chemical entities with `P235`'s created since `2013-06-04` (probably a few hundred thousand). Does the count exclude P235 statement creations, perhaps?

PS, I like to cite the NavelGazer in an upcoming `Scholia Chemistry` paper. Do I just cite this repository?

**Comment by bamyers99** [comment]
Answered on my Wikidata talk page [https://www.wikidata.org/wiki/User_talk:Bamyers99#how_does_it_do_counts_in_NavelGazer](url)
