### ISSUE TITLE
Add "Total" line to #otherdata, #tooldata and #langdata?

### ISSUE THREAD

**Issue by Adafede** [bamyers99/Bambots#9]
Hi @bamyers99, 

Thank you for your awesome tool!

What would you think of adding a total line also to the 3 mentioned tables?

(See screenshot below)
<img width="592" alt="Screenshot 2024-03-01 at 14 36 18" src="https://github.com/bamyers99/Bambots/assets/44283913/a8728de4-6a40-4fc3-9b0e-1947a3928daf">

**Comment by bamyers99** [comment]
Done
